project_name: auth0_exporter
release:
  github:
    owner: raynigon
    name: auth0_exporter
builds:
  - id: auth0_exporter
    goos:
    - linux
    - windows
    - darwin
    goarch:
      - amd64
      - arm64
      - "386"
      - arm
    goarm:
      - "7"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: auth0_exporter.go
    ldflags: -s -w
      -X github.com/raynigon/auth0_exporter/version.version={{.Version}}
      -X github.com/raynigon/auth0_exporter/version.gitSHA={{.Commit}}
      -X github.com/raynigon/auth0_exporter/version.buildTime={{.Date}}
      -extldflags "-static"
    flags: -tags netgo -installsuffix netgo
    binary: auth0_exporter
    hooks: {}
dockers_v2:
  - dockerfile: "./Dockerfile"
    ids:
      - auth0_exporter
    images:
    - "ghcr.io/raynigon/auth0_exporter"
    - "ghcr.io/raynigon/auth0-exporter"
    tags:
      - "latest"
      - "{{ .Tag }}"
      - "v{{ .Major }}"
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/386
archives:
  - id: auth0_exporter
    builds:
      - auth0_exporter
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*
